### ISSUE TITLE
dispatch() missing 1 required positional argument: 'path'

### ISSUE THREAD

**Issue by naughtyGitCat** [TracyWebTech/django-revproxy#100]
urlpatterns = [
    url('api/test', ProxyView.as_view(upstream='http://localhost:8080/'))
]

**Comment by naughtyGitCat** [comment]
django 2.2
python3.6.8

**Comment by naughtyGitCat** [comment]
Request Method: | GET
-- | --
http://127.0.0.1:8000/api/test
2.1.7
TypeError
dispatch() missing 1 required positional argument: 'path'
/Users/psyduck/miniconda3/envs/django/lib/python3.6/site-packages/django/views/generic/base.py in view, line 68
/Users/psyduck/miniconda3/envs/django/bin/python

**Comment by naughtyGitCat** [comment]
and django 2.1 does not have patterns func

**Comment by naughtyGitCat** [comment]
@seocam

**Comment by brianmay** [comment]
I don't think this is a bug. Closing.

**Comment by otuoma** [comment]
This should work for django 3.*
`urlpatterns = [
    path('api/test/<path>/', ProxyView.as_view(upstream='http://localhost:8080/'))
]`

**Comment by nikolis** [comment]
Why was this Issue closed ? Is this project abondaned ? Your suggestions are not helpfull for django version 3.* and there is not documentation on how to use it !

**Comment by max-wittig** [comment]
This helped! It was a bit confusing to me that this regex was required in the path. Thanks!
