### ISSUE TITLE
HTTP 403 Forbidden when post ajax request 

### ISSUE THREAD

**Issue by goodosoft** [TracyWebTech/django-revproxy#101]
"POST /BOE/portal/1905100745/InfoViewAppActions/ajaxUre/ajaxRequest HTTP/1.1" 403 1278

**Comment by brianmay** [comment]
There is not a lot to go on here, unfortunately. I would suspect however that you need to tell revproxy how to authenticate to your remote server.

**Comment by goodosoft** [comment]
try to change http request header with 'get_request_headers',but it not work.

**Comment by brianmay** [comment]
Probably not a revproxy bug. Closing.
