### ISSUE TITLE
What is the lastest Django version does this lib support?

### ISSUE THREAD

**Issue by frank-io** [TracyWebTech/django-revproxy#105]
Hi there,

Does anyone have the idea of what the latest Django version does this library support? Many thanks!

Cheers

**Comment by brianmay** [comment]
Works fine with 1.11 :-)

I tried to bump this up in #104, but this failed. Help appreciated...

Unfortunately the time I have to spend on projects such as this is negative. I imagine making this work with Django 2.2 or even 3.0 would be trivial however.

**Comment by Siecje** [comment]
master works with Django 3.0 but the latest release does not. The latest release version (0.9.15) works with Django 2.2.x.

**Comment by brianmay** [comment]
This should work fine with Django 2.2 and 3.0. Please open a bug report if you encounter any problems.
