### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by vlinhart** [TracyWebTech/django-revproxy#107]
Please release new version with the django 3 support.

I see the necessary fix is in the master already.

thank you very much!

**Comment by brianmay** [comment]
Please help me fix the tests so that they will actually pass under Django 2.2 and Django 3.

At the moment they don't pass, so I really can't claim this project supports Django 3.

https://github.com/TracyWebTech/django-revproxy/pull/104

**Comment by vlinhart** [comment]
should be ok now, please release :-)

**Comment by brianmay** [comment]
Version 0.10.0 now released.
