### ISSUE TITLE
Proxy behind proxy

### ISSUE THREAD

**Issue by coltaan** [TracyWebTech/django-revproxy#67]
Hi there,

Does it use the environment http_proxy and https_proxy variables? I mean should it use?
I've tried to use in a closed (AWS) environment (no outgoing connections without a squid proxy) and looks like doesn't work.

**Comment by coltaan** [comment]
It was a project bug. Sorry. That works.

**Comment by Ashald** [comment]
@coltaan we're seeing the same issue... can you please share your experience - maybe we have similar issue? :)
