### ISSUE TITLE
deploy on pythonanywhere.com,not working

### ISSUE THREAD

**Issue by makelove** [TracyWebTech/django-revproxy#83]
because pythonanywhere limit free accout visit Internet with a white list,need to set up proxy-server(proxy.server:3128) in django 

and my site report Error:
HTTPConnectionPool(host='www.google.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<revproxy.connection.RevProxyHTTPConnection object at 0x7f909e457208>: Failed to establish a new connection: [Errno 101] Network is unreachable',))

But I use urllib3 in teminal to visit www.google.com ,it is working.

How to solve this problem ?
I already setup http_proxy in .bashrc:

export http_proxy='http://proxy.server:3128' 
export https_proxy='http://proxy.server:3128'

**Comment by seocam** [comment]
I'm not sure what you are trying to accomplish here. This is meant to be a reverse proxy for HTTP. Are you trying to use it as a sock s proxy server?

**Comment by seocam** [comment]
I'll close for now and re-open if needed.
