### ISSUE TITLE
Remove Empty Request Headers

### ISSUE THREAD

**Issue by mbande** [TracyWebTech/django-revproxy#93]
it seems that django's ```request.META```, adds many http headers with empty values if they does not exist in client request. e.g. client send a request without ```Content-Type``` header, but request.META contains a ```CONTENT_TYPE``` key with empty string value.
i think revproxy should not send this headers to upstreams, as it does not make sense to send ```Content-Type: ''``` to a web server

**Comment by brianmay** [comment]
Pull requests welcome :-)

**Comment by seocam** [comment]
This is something we want for 1.0 (long coming milestone). 
I'd say it's a duplicate of #33.

**Comment by petrprikryl** [comment]
Just trying [PgHero](https://github.com/ankane/pghero) behing proxy and got error: `"" is not a valid MIME type` in `mime_type.rb`. 

I have tried `request_payload = None` based on #99 but it didn't help. So I wouldn't consider this issue as duplicate od #33.

PgHero is working just fine with patch from #94.
