### ISSUE TITLE
Read Docs page failed to load css 

### ISSUE THREAD

**Issue by ibrahim45** [TracyWebTech/django-revproxy#98]
![rev-proxy-docs](https://user-images.githubusercontent.com/7839955/52780773-0122b400-3071-11e9-94a7-98071e333594.png)

**Comment by brianmay** [comment]
Looks like readthedocs needs to build with Python 3.

Unfortunately I don't appear to have admin rights to this project on
readthedocs, so I cannot make this change....
-- 
Brian May <brian@linuxpenguins.xyz>
https://linuxpenguins.xyz/brian/

**Comment by seocam** [comment]
@brianmay what's your user on readthedocs?

**Comment by brianmay** [comment]
penguin_brian

**Comment by seocam** [comment]
Permission granted ;)

**Comment by brianmay** [comment]
OK, I have fixed the build error.

CSS still fails to load however. Looks like the SSL certificate is expired for https://cdnmedia.readthedocs.org/

**Comment by brianmay** [comment]
Oh, I see. We shouldn't be referencing that site anymore. Problem is fixed here:

https://django-revproxy.readthedocs.io/en/latest/

But default link is for 0.9.3 version, which is old and broken. Should be able to fix,

**Comment by brianmay** [comment]
Should be fixed now.
